apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: myapp
spec:
  hosts:
  - "*"
  gateways:
  - app-gateway
  http:
    - match:
        - uri: 
            exact: "/app"
      rewrite:
        uri: /
      route:
      - destination:
          host: appservice
          subset: v1
        weight: 0
      - destination:
          host: appservice
          subset: v2
        weight: 100      
